version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: product-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - e-commerce

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - e-commerce

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    networks:
      - e-commerce

volumes:
  postgres_data:

networks:
  e-commerce:
    driver: bridge
