apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: product-service.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 80
